"""Comprehensive US stock seed list as fallback when EastMoney API is unavailable.
Covers S&P 500, NASDAQ 100, Dow 30, major ETFs, and popular mid-caps (~800 stocks)."""

US_STOCK_SEED: list[tuple[str, str]] = [
    # ═══ Dow Jones Industrial Average (30) ═══
    ("AAPL", "Apple"), ("MSFT", "Microsoft"), ("AMZN", "Amazon"),
    ("JPM", "JPMorgan Chase"), ("JNJ", "Johnson & Johnson"), ("WMT", "Walmart"),
    ("V", "Visa"), ("PG", "Procter & Gamble"), ("UNH", "UnitedHealth"),
    ("HD", "Home Depot"), ("BAC", "Bank of America"), ("DIS", "Disney"),
    ("NFLX", "Netflix"), ("ADBE", "Adobe"), ("CRM", "Salesforce"),
    ("AMD", "Advanced Micro Devices"), ("INTC", "Intel"), ("QCOM", "Qualcomm"),
    ("TXN", "Texas Instruments"), ("AVGO", "Broadcom"), ("CSCO", "Cisco"),
    ("ORCL", "Oracle"), ("IBM", "IBM"), ("PYPL", "PayPal"),
    ("UBER", "Uber"), ("ABNB", "Airbnb"), ("SNOW", "Snowflake"),
    ("COIN", "Coinbase"), ("PLTR", "Palantir"), ("SQ", "Block"),
    ("SHOP", "Shopify"), ("ZM", "Zoom"), ("SNAP", "Snap"),
    ("RBLX", "Roblox"), ("DASH", "DoorDash"), ("LCID", "Lucid"),
    ("RIVN", "Rivian"), ("NIO", "NIO"), ("BABA", "Alibaba"),
    ("BIDU", "Baidu"), ("JD", "JD.com"), ("PDD", "PDD Holdings"),
    ("XPEV", "XPeng"), ("LI", "Li Auto"), ("TME", "Tencent Music"),
    ("COST", "Costco"), ("TGT", "Target"), ("LOW", "Lowe's"),
    ("CVX", "Chevron"), ("XOM", "Exxon Mobil"), ("PFE", "Pfizer"),
    ("MRK", "Merck"), ("ABBV", "AbbVie"), ("LLY", "Eli Lilly"),
    ("KO", "Coca-Cola"), ("PEP", "PepsiCo"), ("MCD", "McDonald's"),
    ("NKE", "Nike"), ("SBUX", "Starbucks"), ("BA", "Boeing"),
    ("CAT", "Caterpillar"), ("GE", "General Electric"), ("F", "Ford"),
    ("GM", "General Motors"), ("GS", "Goldman Sachs"), ("MS", "Morgan Stanley"),
    ("C", "Citigroup"), ("WFC", "Wells Fargo"), ("BLK", "BlackRock"),
    ("SPY", "SPDR S&P 500 ETF"), ("QQQ", "Invesco QQQ Trust"), ("IWM", "iShares Russell 2000"),
    ("DIA", "SPDR Dow Jones ETF"), ("VOO", "Vanguard S&P 500 ETF"), ("VTI", "Vanguard Total Stock"),
    ("XLF", "Financial Select Sector"), ("XLK", "Technology Select Sector"),
    ("XLE", "Energy Select Sector"), ("XLV", "Health Care Select Sector"),
    ("SMH", "VanEck Semiconductor ETF"), ("ARKK", "ARK Innovation ETF"),

    # ═══ Information Technology ═══
    ("AAPL", "Apple Inc."), ("MSFT", "Microsoft Corp."), ("NVDA", "NVIDIA Corp."),
    ("AVGO", "Broadcom Inc."), ("ORCL", "Oracle Corp."), ("CRM", "Salesforce Inc."),
    ("ADBE", "Adobe Inc."), ("CSCO", "Cisco Systems"), ("IBM", "IBM"),
    ("ACN", "Accenture"), ("INTU", "Intuit Inc."), ("NOW", "ServiceNow"),
    ("AMD", "Advanced Micro Devices"), ("INTC", "Intel Corp."), ("QCOM", "Qualcomm Inc."),
    ("TXN", "Texas Instruments"), ("AMAT", "Applied Materials"), ("LRCX", "Lam Research"),
    ("KLAC", "KLA Corp."), ("MU", "Micron Technology"), ("ADI", "Analog Devices"),
    ("MRVL", "Marvell Technology"), ("MPWR", "Monolithic Power"), ("ON", "ON Semiconductor"),
    ("ASML", "ASML Holding"), ("TSM", "Taiwan Semiconductor"), ("ARM", "ARM Holdings"),
    ("SNOW", "Snowflake Inc."), ("PLTR", "Palantir Technologies"), ("TEAM", "Atlassian"),
    ("DDOG", "Datadog"), ("CRWD", "CrowdStrike Holdings"), ("ZS", "Zscaler"),
    ("PANW", "Palo Alto Networks"), ("FTNT", "Fortinet"), ("NET", "Cloudflare"),
    ("MDB", "MongoDB"), ("HUBS", "HubSpot"), ("TTD", "The Trade Desk"),
    ("OKTA", "Okta Inc."), ("APP", "AppLovin"), ("MSTR", "MicroStrategy"),
    ("GTLB", "GitLab"), ("CFLT", "Confluent"), ("S", "SentinelOne"),
    ("PATH", "UiPath"), ("U", "Unity Software"), ("SMCI", "Super Micro Computer"),
    ("ANET", "Arista Networks"), ("DELL", "Dell Technologies"), ("HPQ", "HP Inc."),
    ("HPE", "Hewlett Packard Enterprise"), ("WDAY", "Workday"), ("ADSK", "Autodesk"),
    ("FIS", "Fidelity National Information"), ("FISV", "Fiserv"), ("GPN", "Global Payments"),
    ("MA", "Mastercard"), ("V", "Visa Inc."), ("PYPL", "PayPal Holdings"),
    ("SQ", "Block Inc."), ("AFRM", "Affirm Holdings"), ("SOFI", "SoFi Technologies"),

    # ═══ Communication Services ═══
    ("GOOGL", "Alphabet Inc."), ("META", "Meta Platforms"), ("NFLX", "Netflix Inc."),
    ("DIS", "Walt Disney Co."), ("CMCSA", "Comcast Corp."), ("T", "AT&T Inc."),
    ("VZ", "Verizon Communications"), ("TMUS", "T-Mobile US"), ("CHTR", "Charter Communications"),
    ("WBD", "Warner Bros Discovery"), ("PARA", "Paramount Global"), ("LYV", "Live Nation"),
    ("SNAP", "Snap Inc."), ("PINS", "Pinterest"), ("MTCH", "Match Group"),
    ("SPOT", "Spotify Technology"), ("RDDT", "Reddit"), ("DJT", "Trump Media"),

    # ═══ Consumer Discretionary ═══
    ("AMZN", "Amazon.com"), ("TSLA", "Tesla Inc."), ("HD", "Home Depot"),
    ("LOW", "Lowe's Companies"), ("MCD", "McDonald's Corp."), ("NKE", "Nike Inc."),
    ("SBUX", "Starbucks Corp."), ("TGT", "Target Corp."), ("TJX", "TJX Companies"),
    ("BKNG", "Booking Holdings"), ("MAR", "Marriott International"), ("HLT", "Hilton Worldwide"),
    ("CMG", "Chipotle Mexican Grill"), ("YUM", "Yum! Brands"), ("DHI", "D.R. Horton"),
    ("LEN", "Lennar Corp."), ("PHM", "PulteGroup"), ("NVR", "NVR Inc."),
    ("ROST", "Ross Stores"), ("DG", "Dollar General"), ("DLTR", "Dollar Tree"),
    ("AZO", "AutoZone"), ("ORLY", "O'Reilly Automotive"), ("ULTA", "Ulta Beauty"),
    ("LULU", "Lululemon Athletica"), ("RCL", "Royal Caribbean"), ("CCL", "Carnival Corp."),
    ("TSCO", "Tractor Supply"), ("BBY", "Best Buy"), ("GME", "GameStop"),
    ("AMC", "AMC Entertainment"), ("CVNA", "Carvana"), ("W", "Wayfair"),
    ("ETSY", "Etsy"), ("EBAY", "eBay"), ("CPNG", "Coupang"),
    ("SE", "Sea Limited"), ("MELI", "MercadoLibre"), ("BABA", "Alibaba Group"),
    ("JD", "JD.com"), ("PDD", "PDD Holdings"), ("BIDU", "Baidu Inc."),
    ("TME", "Tencent Music"), ("NTES", "NetEase"), ("BILI", "Bilibili"),
    ("VIPS", "Vipshop Holdings"), ("YUMC", "Yum China"), ("BEKE", "KE Holdings"),
    ("TAL", "TAL Education"), ("F", "Ford Motor"), ("GM", "General Motors"),
    ("RIVN", "Rivian Automotive"), ("LCID", "Lucid Group"), ("STLA", "Stellantis"),
    ("TM", "Toyota Motor"), ("HMC", "Honda Motor"), ("RACE", "Ferrari"),
    ("NIO", "NIO Inc."), ("XPEV", "XPeng"), ("LI", "Li Auto"),
    ("UBER", "Uber Technologies"), ("LYFT", "Lyft"), ("DASH", "DoorDash"),
    ("ABNB", "Airbnb"), ("EXPE", "Expedia Group"), ("DKNG", "DraftKings"),
    ("PENN", "PENN Entertainment"), ("WYNN", "Wynn Resorts"), ("LVS", "Las Vegas Sands"),
    ("MGM", "MGM Resorts"), ("CZR", "Caesars Entertainment"), ("H", "Hyatt Hotels"),

    # ═══ Consumer Staples ═══
    ("WMT", "Walmart Inc."), ("COST", "Costco Wholesale"), ("PG", "Procter & Gamble"),
    ("KO", "Coca-Cola Co."), ("PEP", "PepsiCo"), ("PM", "Philip Morris International"),
    ("MO", "Altria Group"), ("EL", "Estee Lauder"), ("CL", "Colgate-Palmolive"),
    ("KMB", "Kimberly-Clark"), ("GIS", "General Mills"), ("KHC", "Kraft Heinz"),
    ("MDLZ", "Mondelez International"), ("HSY", "Hershey Co."), ("STZ", "Constellation Brands"),
    ("BF.B", "Brown-Forman"), ("MNST", "Monster Beverage"), ("KDP", "Keurig Dr Pepper"),
    ("SYY", "Sysco Corp."), ("ADM", "Archer-Daniels-Midland"), ("BG", "Bunge Global"),
    ("TSN", "Tyson Foods"), ("HRL", "Hormel Foods"), ("CPB", "Campbell Soup"),
    ("SJM", "J.M. Smucker"), ("CAG", "Conagra Brands"), ("LW", "Lamb Weston"),
    ("MKC", "McCormick & Co."), ("CLX", "Clorox Co."), ("CHD", "Church & Dwight"),

    # ═══ Energy ═══
    ("XOM", "Exxon Mobil Corp."), ("CVX", "Chevron Corp."), ("COP", "ConocoPhillips"),
    ("EOG", "EOG Resources"), ("SLB", "Schlumberger"), ("PSX", "Phillips 66"),
    ("MPC", "Marathon Petroleum"), ("VLO", "Valero Energy"), ("OXY", "Occidental Petroleum"),
    ("HAL", "Halliburton"), ("KMI", "Kinder Morgan"), ("WMB", "Williams Companies"),
    ("LNG", "Cheniere Energy"), ("DVN", "Devon Energy"), ("PXD", "Pioneer Natural Resources"),
    ("FANG", "Diamondback Energy"), ("MRO", "Marathon Oil"), ("HES", "Hess Corp."),
    ("BKR", "Baker Hughes"), ("APA", "APA Corp."), ("CTRA", "Coterra Energy"),
    ("EQT", "EQT Corp."), ("OVV", "Ovintiv"), ("CHK", "Chesapeake Energy"),

    # ═══ Financials ═══
    ("BRK.B", "Berkshire Hathaway"), ("JPM", "JPMorgan Chase & Co."), ("BAC", "Bank of America"),
    ("WFC", "Wells Fargo & Co."), ("GS", "Goldman Sachs Group"), ("MS", "Morgan Stanley"),
    ("C", "Citigroup Inc."), ("BLK", "BlackRock"), ("SCHW", "Charles Schwab"),
    ("AXP", "American Express"), ("COF", "Capital One Financial"), ("USB", "U.S. Bancorp"),
    ("PNC", "PNC Financial Services"), ("BK", "BNY Mellon"), ("TFC", "Truist Financial"),
    ("AIG", "American International Group"), ("MET", "MetLife"), ("PRU", "Prudential Financial"),
    ("BX", "Blackstone"), ("KKR", "KKR & Co."), ("APO", "Apollo Global Management"),
    ("ICE", "Intercontinental Exchange"), ("CME", "CME Group"), ("MMC", "Marsh & McLennan"),
    ("CB", "Chubb Limited"), ("AFL", "Aflac"), ("ALL", "Allstate Corp."),
    ("TRV", "Travelers Companies"), ("PGR", "Progressive Corp."), ("MCO", "Moody's Corp."),
    ("SPGI", "S&P Global"), ("NDAQ", "Nasdaq Inc."), ("MSCI", "MSCI Inc."),
    ("HOOD", "Robinhood Markets"), ("SOFI", "SoFi Technologies"), ("AFRM", "Affirm Holdings"),
    ("COIN", "Coinbase Global"), ("MARA", "Marathon Digital Holdings"), ("RIOT", "Riot Platforms"),

    # ═══ Health Care ═══
    ("JNJ", "Johnson & Johnson"), ("UNH", "UnitedHealth Group"), ("PFE", "Pfizer Inc."),
    ("MRK", "Merck & Co."), ("ABBV", "AbbVie Inc."), ("LLY", "Eli Lilly & Co."),
    ("AMGN", "Amgen"), ("BMY", "Bristol-Myers Squibb"), ("GILD", "Gilead Sciences"),
    ("CVS", "CVS Health"), ("CI", "Cigna Group"), ("HUM", "Humana Inc."),
    ("ISRG", "Intuitive Surgical"), ("SYK", "Stryker Corp."), ("BSX", "Boston Scientific"),
    ("MDT", "Medtronic"), ("EW", "Edwards Lifesciences"), ("DXCM", "Dexcom"),
    ("VRTX", "Vertex Pharmaceuticals"), ("REGN", "Regeneron Pharmaceuticals"), ("BIIB", "Biogen"),
    ("MRNA", "Moderna"), ("BNTX", "BioNTech"), ("TDOC", "Teladoc Health"),
    ("ZTS", "Zoetis"), ("TMO", "Thermo Fisher Scientific"), ("DHR", "Danaher Corp."),
    ("ABT", "Abbott Laboratories"), ("SYK", "Stryker Corp."), ("BDX", "Becton Dickinson"),
    ("A", "Agilent Technologies"), ("IQV", "IQVIA Holdings"), ("HCA", "HCA Healthcare"),
    ("ELV", "Elevance Health"), ("CNC", "Centene Corp."), ("MOH", "Molina Healthcare"),
    ("DGX", "Quest Diagnostics"), ("LH", "Labcorp Holdings"), ("MCK", "McKesson Corp."),
    ("ABC", "AmerisourceBergen"), ("CAH", "Cardinal Health"), ("WBA", "Walgreens Boots Alliance"),

    # ═══ Industrials ═══
    ("BA", "Boeing Co."), ("CAT", "Caterpillar Inc."), ("GE", "General Electric"),
    ("HON", "Honeywell International"), ("UPS", "United Parcel Service"), ("UNP", "Union Pacific"),
    ("RTX", "RTX Corp."), ("LMT", "Lockheed Martin"), ("NOC", "Northrop Grumman"),
    ("DE", "Deere & Co."), ("ETN", "Eaton Corp."), ("ITW", "Illinois Tool Works"),
    ("MMM", "3M Co."), ("EMR", "Emerson Electric"), ("GD", "General Dynamics"),
    ("FDX", "FedEx Corp."), ("DAL", "Delta Air Lines"), ("UAL", "United Airlines Holdings"),
    ("LUV", "Southwest Airlines"), ("AAL", "American Airlines"), ("CSX", "CSX Corp."),
    ("NSC", "Norfolk Southern"), ("CP", "Canadian Pacific"), ("CNI", "Canadian National Railway"),
    ("JCI", "Johnson Controls"), ("CARR", "Carrier Global"), ("OTIS", "Otis Worldwide"),
    ("IR", "Ingersoll Rand"), ("ROK", "Rockwell Automation"), ("PH", "Parker Hannifin"),
    ("CMI", "Cummins"), ("PCAR", "PACCAR"), ("FAST", "Fastenal"),
    ("GWW", "W.W. Grainger"), ("URI", "United Rentals"), ("WAB", "Westinghouse Air Brake"),
    ("PNR", "Pentair"), ("DOV", "Dover Corp."), ("XYL", "Xylem"),
    ("IEX", "IDEX Corp."), ("NDSN", "Nordson Corp."), ("GGG", "Graco Inc."),
    ("AXON", "Axon Enterprise"), ("HEI", "HEICO Corp."), ("TDG", "TransDigm Group"),
    ("TXT", "Textron"), ("LHX", "L3Harris Technologies"), ("HWM", "Howmet Aerospace"),
    ("MAS", "Masco Corp."), ("BLDR", "Builders FirstSource"), ("TT", "Trane Technologies"),

    # ═══ Real Estate ═══
    ("PLD", "Prologis"), ("AMT", "American Tower"), ("CCI", "Crown Castle"),
    ("EQIX", "Equinix"), ("SPG", "Simon Property Group"), ("O", "Realty Income"),
    ("WELL", "Welltower"), ("PSA", "Public Storage"), ("AVB", "AvalonBay Communities"),
    ("EQR", "Equity Residential"), ("INVH", "Invitation Homes"), ("MAA", "Mid-America Apartment"),
    ("ESS", "Essex Property Trust"), ("UDR", "UDR Inc."), ("CPT", "Camden Property Trust"),
    ("DLR", "Digital Realty Trust"), ("EXR", "Extra Space Storage"), ("VTR", "Ventas"),
    ("PEAK", "Healthpeak Properties"), ("SBAC", "SBA Communications"), ("STAG", "STAG Industrial"),
    ("REXR", "Rexford Industrial Realty"), ("COLD", "Americold Realty Trust"),

    # ═══ Materials ═══
    ("LIN", "Linde"), ("FCX", "Freeport-McMoRan"), ("NEM", "Newmont Corp."),
    ("DOW", "Dow Inc."), ("DD", "DuPont de Nemours"), ("APD", "Air Products"),
    ("SHW", "Sherwin-Williams"), ("ECL", "Ecolab"), ("NUE", "Nucor Corp."),
    ("VMC", "Vulcan Materials"), ("MLM", "Martin Marietta Materials"), ("CTVA", "Corteva"),
    ("CF", "CF Industries"), ("MOS", "Mosaic Co."), ("FMC", "FMC Corp."),
    ("BALL", "Ball Corp."), ("PKG", "Packaging Corp. of America"), ("AVY", "Avery Dennison"),
    ("IP", "International Paper"), ("WRK", "WestRock"), ("AMCR", "Amcor"),
    ("GOLD", "Barrick Gold"), ("AEM", "Agnico Eagle Mines"), ("FNV", "Franco-Nevada"),
    ("WPM", "Wheaton Precious Metals"), ("CE", "Celanese Corp."), ("EMN", "Eastman Chemical"),
    ("ALB", "Albemarle Corp."), ("LYB", "LyondellBasell Industries"), ("PPG", "PPG Industries"),

    # ═══ Utilities ═══
    ("NEE", "NextEra Energy"), ("DUK", "Duke Energy"), ("SO", "Southern Co."),
    ("D", "Dominion Energy"), ("AEP", "American Electric Power"), ("SRE", "Sempra"),
    ("EXC", "Exelon Corp."), ("XEL", "Xcel Energy"), ("ED", "Consolidated Edison"),
    ("PEG", "Public Service Enterprise Group"), ("EIX", "Edison International"), ("WEC", "WEC Energy Group"),
    ("DTE", "DTE Energy"), ("AEE", "Ameren Corp."), ("PPL", "PPL Corp."),
    ("FE", "FirstEnergy"), ("ETR", "Entergy Corp."), ("ES", "Eversource Energy"),
    ("CMS", "CMS Energy"), ("AWK", "American Water Works"), ("VST", "Vistra Corp."),
    ("NRG", "NRG Energy"), ("CEG", "Constellation Energy"), ("ATO", "Atmos Energy"),

    # ═══ Major ETFs ═══
    ("SPY", "SPDR S&P 500 ETF Trust"), ("IVV", "iShares Core S&P 500 ETF"),
    ("VOO", "Vanguard S&P 500 ETF"), ("QQQ", "Invesco QQQ Trust"),
    ("QQQM", "Invesco NASDAQ 100 ETF"), ("IWM", "iShares Russell 2000 ETF"),
    ("DIA", "SPDR Dow Jones Industrial Average ETF"), ("VTI", "Vanguard Total Stock Market ETF"),
    ("VEA", "Vanguard FTSE Developed Markets ETF"), ("VWO", "Vanguard FTSE Emerging Markets ETF"),
    ("EFA", "iShares MSCI EAFE ETF"), ("EEM", "iShares MSCI Emerging Markets ETF"),
    ("FXI", "iShares China Large-Cap ETF"), ("KWEB", "KraneShares CSI China Internet ETF"),
    ("GLD", "SPDR Gold Trust"), ("SLV", "iShares Silver Trust"),
    ("USO", "United States Oil Fund"), ("UNG", "United States Natural Gas Fund"),
    ("TLT", "iShares 20+ Year Treasury Bond ETF"), ("LQD", "iShares iBoxx Inv Grade Corp Bond ETF"),
    ("HYG", "iShares iBoxx High Yield Corp Bond ETF"), ("AGG", "iShares Core US Aggregate Bond ETF"),
    ("BND", "Vanguard Total Bond Market ETF"), ("BIL", "SPDR Bloomberg 1-3 Month T-Bill ETF"),
    ("ARKK", "ARK Innovation ETF"), ("ARKW", "ARK Next Generation Internet ETF"),
    ("ARKG", "ARK Genomic Revolution ETF"), ("ARKF", "ARK Fintech Innovation ETF"),
    ("XLF", "Financial Select Sector SPDR"), ("XLK", "Technology Select Sector SPDR"),
    ("XLV", "Health Care Select Sector SPDR"), ("XLY", "Consumer Discretionary Select Sector SPDR"),
    ("XLP", "Consumer Staples Select Sector SPDR"), ("XLE", "Energy Select Sector SPDR"),
    ("XLI", "Industrial Select Sector SPDR"), ("XLB", "Materials Select Sector SPDR"),
    ("XLU", "Utilities Select Sector SPDR"), ("XLRE", "Real Estate Select Sector SPDR"),
    ("XLC", "Communication Services Select Sector SPDR"), ("SMH", "VanEck Semiconductor ETF"),
    ("SOXX", "iShares Semiconductor ETF"), ("ICLN", "iShares Global Clean Energy ETF"),
    ("TAN", "Invesco Solar ETF"), ("URA", "Global X Uranium ETF"),

    # ═══ Additional Popular Stocks ═══
    ("PBR", "Petrobras"), ("VALE", "Vale S.A."), ("ITUB", "Itau Unibanco"),
    ("BBD", "Banco Bradesco"), ("NU", "Nu Holdings"), ("XP", "XP Inc."),
    ("GGB", "Gerdau"), ("ERJ", "Embraer"), ("PAGS", "PagSeguro Digital"),
    ("STNE", "StoneCo"), ("BZ", "Kanzhun"), ("ATHM", "Autohome"),
    ("ZEEKR", "Zeekr Intelligent Technology"), ("SYM", "Symbotic"),
    ("RKLB", "Rocket Lab USA"), ("ASTS", "AST SpaceMobile"),
    ("LUNR", "Intuitive Machines"), ("IONQ", "IonQ"),
    ("QS", "QuantumScape"), ("LCID", "Lucid Group"),
    ("FUBO", "fuboTV"), ("CHWY", "Chewy"), ("BYND", "Beyond Meat"),
    ("PTON", "Peloton Interactive"), ("IRBT", "iRobot"),
    ("KSS", "Kohl's"), ("M", "Macy's"), ("JWN", "Nordstrom"),
    ("GPS", "Gap Inc."), ("ANF", "Abercrombie & Fitch"), ("AEO", "American Eagle Outfitters"),
    ("CROX", "Crocs"), ("DECK", "Deckers Outdoor"), ("SKX", "Skechers"),
    ("FL", "Foot Locker"), ("RL", "Ralph Lauren"), ("TPR", "Tapestry"),
    ("PVH", "PVH Corp."), ("LEVI", "Levi Strauss"), ("UAA", "Under Armour"),
    ("GPS", "Gap"), ("VSCO", "Victoria's Secret"), ("BOOT", "Boot Barn"),
    ("SFM", "Sprouts Farmers Market"), ("KR", "Kroger"), ("ACI", "Albertsons Companies"),
    ("CASY", "Casey's General Stores"), ("MUSA", "Murphy USA"), ("BJ", "BJ's Wholesale Club"),
    ("PLNT", "Planet Fitness"), ("HRB", "H&R Block"), ("INTU", "Intuit"),
    ("TOST", "Toast"), ("BILL", "BILL Holdings"), ("DOCN", "DigitalOcean"),
    ("RNG", "RingCentral"), ("BOX", "Box Inc."), ("DBX", "Dropbox"),
    ("TWLO", "Twilio"), ("ZI", "ZoomInfo Technologies"), ("FIVN", "Five9"),
    ("NCNO", "nCino"), ("AI", "C3.ai"), ("VERX", "Vertex Inc."),
    ("GWRE", "Guidewire Software"), ("MNDY", "monday.com"), ("ASAN", "Asana"),
    ("SMAR", "Smartsheet"), ("WIX", "Wix.com"), ("FROG", "JFrog"),
    ("GTLB", "GitLab"), ("S", "SentinelOne"), ("CXM", "Sprinklr"),
    ("BRZE", "Braze"), ("PWSC", "PowerSchool Holdings"), ("INST", "Instructure Holdings"),

    # ═══ Energy Midstream & More ═══
    ("OKE", "ONEOK"), ("TRGP", "Targa Resources"), ("ET", "Energy Transfer"),
    ("EPD", "Enterprise Products Partners"), ("MMP", "Magellan Midstream Partners"),
    ("PBA", "Pembina Pipeline"), ("ENB", "Enbridge"), ("TRP", "TC Energy"),
    ("WES", "Western Midstream"), ("AM", "Antero Midstream"), ("DTM", "DT Midstream"),
    ("HESM", "Hess Midstream"), ("ENLC", "EnLink Midstream"),

    # ═══ REITs ═══
    ("IRM", "Iron Mountain"), ("GLPI", "Gaming and Leisure Properties"),
    ("WPC", "W.P. Carey"), ("LAMR", "Lamar Advertising"), ("EPR", "EPR Properties"),
    ("OHI", "Omega Healthcare Investors"), ("NNN", "NNN REIT"), ("FRT", "Federal Realty"),
    ("REG", "Regency Centers"), ("KIM", "Kimco Realty"), ("BXP", "Boston Properties"),
    ("ARE", "Alexandria Real Estate"), ("KRC", "Kilroy Realty"), ("HIW", "Highwoods Properties"),
    ("DEI", "Douglas Emmett"), ("CUZ", "Cousins Properties"), ("SLG", "SL Green Realty"),
    ("VNO", "Vornado Realty Trust"), ("JBGS", "JBG SMITH Properties"),
]
